name: ScreenBreak
options:
  bundleIdPrefix: com.screenbreak
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.38.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: "11.0.0"

targets:
  ScreenBreak:
    type: application
    platform: iOS
    sources:
      - path: ScreenBreak
    resources:
      - path: ScreenBreak/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screenbreak.app
        INFOPLIST_FILE: ScreenBreak/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: ScreenBreak/Resources/ScreenBreak.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE: true
        SWIFT_EMIT_LOC_STRINGS: "YES"
    dependencies:
      - target: DeviceActivityMonitorExtension
      - target: ShieldConfigurationExtension
      - target: ShieldActionExtension
      - package: GoogleMobileAds
    entitlements:
      path: ScreenBreak/Resources/ScreenBreak.entitlements
    preBuildScripts: []
    postBuildScripts: []

  DeviceActivityMonitorExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: DeviceActivityMonitorExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screenbreak.app.DeviceActivityMonitorExtension
        INFOPLIST_FILE: DeviceActivityMonitorExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: DeviceActivityMonitorExtension/DeviceActivityMonitorExtension.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: false
    entitlements:
      path: DeviceActivityMonitorExtension/DeviceActivityMonitorExtension.entitlements
    dependencies:
      - sdk: DeviceActivity.framework
      - sdk: ManagedSettings.framework
      - sdk: FamilyControls.framework

  ShieldConfigurationExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShieldConfigurationExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screenbreak.app.ShieldConfigurationExtension
        INFOPLIST_FILE: ShieldConfigurationExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: ShieldConfigurationExtension/ShieldConfigurationExtension.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: false
    entitlements:
      path: ShieldConfigurationExtension/ShieldConfigurationExtension.entitlements
    dependencies:
      - sdk: ManagedSettings.framework
      - sdk: ManagedSettingsUI.framework
      - sdk: FamilyControls.framework

  ShieldActionExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShieldActionExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screenbreak.app.ShieldActionExtension
        INFOPLIST_FILE: ShieldActionExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: ShieldActionExtension/ShieldActionExtension.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: false
    entitlements:
      path: ShieldActionExtension/ShieldActionExtension.entitlements
    dependencies:
      - sdk: ManagedSettings.framework
      - sdk: ManagedSettingsUI.framework
      - sdk: FamilyControls.framework

schemes:
  ScreenBreak:
    build:
      targets:
        ScreenBreak: all
        DeviceActivityMonitorExtension: all
        ShieldConfigurationExtension: all
        ShieldActionExtension: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
